### ISSUE TITLE
Feature: Hulo Button

### ISSUE THREAD

**Issue by Kadastross** [Kadastross/Novice-to-Expert#1]
A big blue hulo button required

**Comment by paridhigulati** [comment]
-.-- --- -.-.-- / - ..- -. -.. ... / .-.. . - / -- . / .... . .-.. .--. / ..- / .-- .. - .... / .... ..- .-.. --- / -... ..- - - --- -.

**Comment by Kadastross** [comment]
> -.-- --- -.-.-- / - ..- -. -.. ... / .-.. . - / -- . / .... . .-.. .--. / ..- / .-- .. - .... / .... ..- .-.. --- / -... ..- - - --- -.

Congrats Gulati! This issue is assigned to you, thanks to your wonderful comment up here.

**Comment by Kadastross** [comment]
this fixes #1
